Hyprland be HyprPog

diff --git a/scripts/getnf b/scripts/getnf
--- a/scripts/getnf
+++ b/scripts/getnf
@@ -3,102 +3,222 @@
 #defining variables
 nerdfontsrepo='https://api.github.com/repos/ryanoasis/nerd-fonts'
 aFontInstalled="False"
-keepArchives="False"
-distDir="$HOME/.local/share/fonts"
-downDir="$(command -V xdg-user-dir &> /dev/null && xdg-user-dir DOWNLOAD || echo "$HOME/Downloads")/NerdFonts"
+removeZipFiles="True"
+dist_dir="$HOME/.local/share/fonts"
+down_dir="$(command -V xdg-user-dir &>/dev/null && xdg-user-dir DOWNLOAD || echo "$HOME/Downloads")/NerdFonts"
+cache_dir="$HOME/.cache/nerdFonts"
+update_fonts="False"
+force_update="False"
 os=$(uname)
 
-# help message
-usage() {
-    echo "getNF: A Better way to install NerdFonts"
-    echo ""
-    echo "Usage:"
-    echo "-h print this help message and exit"
-    echo "-k Keep the downloaded archives"
-    echo ""
-}
-
-# setting flags
-while getopts :hk option; do
-    case "${option}" in
-        h) usage && exit 0 ;;
-        k) keepArchives="True" ;;
-        *) usage && exit 0
-    esac
-done
+# Set colors
+RED=$(tput setaf 1)
+GREEN=$(tput setaf 2)
+BLUE=$(tput setaf 4)
+RESET=$(tput sgr0)
 
 # For Macs, need to set a few different things
 if [[ "$os" == 'Darwin' ]]; then
-    distDir="$HOME/Library/Fonts"
+	dist_dir="$HOME/Library/Fonts"
+	cache_dir="$HOME/Library/Caches/NerdFonts"
 fi
 
-# Check if the distDir and downDir exists, if it doesn't, create it
-[ -d "$distDir" ] || mkdir -p "$distDir" && echo "Fonts Directory exists, good" 
-[ -d "$downDir" ] || mkdir -p "$downDir" && echo "Download Fonts Directory exists, good" 
+# help message
+usage() {
+	echo "${BLUE}getNF: A Better way to install NerdFonts${RESET}"
+	echo ""
+	echo "${BLUE}Usage:${RESET}"
+	echo "${BLUE}-h print this help message and exit"
+	echo "-f force reinstall an already installed font"
+	echo "-k Keep the downloaded fonts zip files${RESET}"
+	echo ""
+	echo "- ${BLUE}Choose one or more fonts (by index/number) to install"
+	echo "- Hit Return/Enter to install the selected fonts"
+	echo "- Type the index/number corresponding to 'Quit' to cancel${RESET}"
+	echo ""
+}
 
-# get font names
-nerdFonts=$(curl --silent "$nerdfontsrepo/contents/patched-fonts?ref=master" | \
-                grep "name" | \
-                awk -F":" '{print $2}' | \
-                sed 's/["",]//g;/install\.ps1/d')
-
-#get the latest release number from NerdFonts github repo
-release=$(curl --silent "$nerdfontsrepo/releases/latest" | \
-  grep -i tag_name | cut -d'"' -f4)
-
-
-# use fzf to select the fonts to be installed
-listFonts=$(printf '%s\n' "${nerdFonts[@]}" | fzf -m)
-
-#loop over the selected fonts in listFonts, download and install them
-for i in $listFonts; do
-    checkFont=$(fc-list | grep -i "$i")
-    if [ -z "$checkFont" ]; then #If the font already is installed, skip it
-	echo "$i font download started" &&
-            pushd "$downDir" > /dev/null &&
-	    #download the font
-	    curl -LJO -\# "https://github.com/ryanoasis/nerd-fonts/releases/download/$release/$i.zip" \
-		 -o "$i.zip" --create-dirs &&
-	    echo "$i font download finished" &&
-	    echo "$i font unziping started" &&
-	    #Unzipe the downloaded archive
-	    # unzip -qq "$downDir/$i.zip" -d "$distDir" &&
-            unzip -qq "$i.zip" -d "$distDir" &&
-	    echo "$i font unzipping finished" &&
-	    echo "Font $i Installed" &&
-	    installedFontName=$(curl --silent "$nerdfontsrepo/contents/patched-fonts/$i/Regular/complete?ref=master" | \
-				    grep ".ttf" | \
-				    awk -F ":" 'FNR == 1 {print $2}' | \
-				    awk '{print $1}' | \
-				    sed 's/"//g') &&
-            #set this variable to true so that the font cache get's updated
-            aFontInstalled=True && # We do this before the Additional info, so  even if it fails the font cache will be refreshed
-            #Additional info, only if we can get the real font name
-            if [ -n "$installedFontName" ]; then
-                echo "$i provides:" &&
-	        fc-list | grep -i "$installedFontName" | \
-		    awk -F "/" '{print $7}' | \
-		    sed 's/style\=//' |  \
-		    awk -F ":" 'BEGIN {print "FONT NAME" " | " "FILE NAME" " | " "STYLE"} {print $2 " | " $1 " | " $3}' | \
-            	    column -s "|" -t
-            fi
-            popd > /dev/null
-    else
-	echo "Font $i already installed"
-    fi
+# Setting flags
+while getopts :hkf option; do
+	case "${option}" in
+	h) usage && exit 0 ;;
+	k) removeZipFiles="False" ;;
+	f) force_update="True" ;;
+	*) usage && exit 0 ;;
+	esac
 done
 
-# If a font was installed, Update the font cache and remove the archive
-if [ "$aFontInstalled" = "True" ]; then
-    echo "Regenerating fc-cache"
-    fc-cache -f  2>&1 && echo "fc-cache: regeneration succeeded!"
-    #check if the user hasn't chooen to keep the updated, if not, remove them
-    if [ "$keepArchives" = "False" ]; then
-        echo "Removing zip font files in $downDir" &&
-	rm $downDir/*.zip
-    else
-	echo "The archive files are in $downDir"
-    fi
+# Check if the distDir and downDir exists, if it doesn't, create it
+[ -d "$dist_dir" ] && echo "${BLUE}Fonts directory exists, good.${RESET}" || (mkdir -p "$dist_dir" && echo "${GREEN}Created the fonts directory.${RESET}")
+[ -d "$down_dir" ] && echo "${BLUE}Fonts download directory exists, good.${RESET}" || (mkdir -p "$down_dir" && echo "${GREEN}Created fonts download directory..${RESET}")
+[ -d "$cache_dir" ] || mkdir -p "$cache_dir"
+
+## Handle release version
+# Set the name of the file to store the release number
+release_file="$cache_dir/release.txt"
+# Get the local release version
+[ -f "$release_file" ] && cached_release=$(cat "$release_file") || cached_release=""
+# Get the latest release number from NerdFonts github repo
+release=$(curl --silent "$nerdfontsrepo/releases/latest" |
+	awk -F'"' '/tag_name/ {print $4}')
+# Compare the latest release number with the cached release number
+if [ "$release" != "$cached_release" ]; then
+	update_fonts=True
+	# Update the cached release number
+	echo "$release" >"$release_file"
 fi
 
-echo "All is done!"
+## Handle the font names
+# Download the file list and extract the font names
+font_list=$(curl -s "$nerdfontsrepo/contents/patched-fonts?ref=master" |
+	awk -F'"' '/name/ {print $4}')
+# Convert the list of fonts into an array of fonts
+declare -a fonts
+# Read the input string and populate the array, we do this to get rid of the `readarray` command
+while IFS= read -r line; do
+	fonts+=("$line")
+done <<<"$font_list"
+#define a file for the installed fonts names to be stored in
+installed_fonts_file="$cache_dir/installed.txt"
+[ -f "$installed_fonts_file" ] && installed_fonts_list=$(cat "$installed_fonts_file") || installed_fonts_list=()
+# Convert the list of installed fonts into an array of fonts
+declare -a installed_fonts
+while IFS= read -r line; do
+	installed_fonts+=("$line")
+done <<<"$installed_fonts_list"
+# a list of currently selectd fonts
+selected_fonts=()
+
+# Remove installed fonts from the list of all fonts if there is no new release
+if [[ $update_fonts = "False" ]]; then
+	available_fonts=()
+	for font in "${fonts[@]}"; do
+		if [[ ! " ${installed_fonts[@]} " =~ " ${font} " ]]; then
+			available_fonts+=("$font")
+		fi
+	done
+else
+	echo "" >"$installed_fonts_file"
+	available_fonts=("${fonts[@]}")
+fi
+
+function download_font() {
+	echo "${BLUE}$1 download started...${RESET}"
+	curl -LJO# "https://github.com/ryanoasis/nerd-fonts/releases/download/$release/$1.zip"
+	echo "${GREEN}$1 download finished${RESET}"
+}
+
+function install_font() {
+	echo "${BLUE}$1 instalation started...${RESET}"
+	unzip -qqo "$1.zip" -d "$dist_dir"
+	echo "${GREEN}$1 installation finished${RESET}"
+}
+
+function remove_zip_files() {
+	echo "${BLUE}Removing downloaded zip files from $down_dir...${RESET}"
+	for font in "${selected_fonts[@]}"; do
+		rm $down_dir/$font.zip
+	done
+	echo "${GREEN}Downloaded zip files removal suceeded!${RESET}"
+}
+
+function update_fonts_cache() {
+	echo "${BLUE}Updating fc-cache...${RESET}"
+	fc-cache -f 2>&1
+	echo "${GREEN}fc-cache: update succeeded!${RESET}"
+}
+
+# Remove already selected fonts from the menu
+if [ $force_update = "True" ]; then
+	font_options=("${fonts[@]}")
+else
+	font_options=("${available_fonts[@]}")
+fi
+# Define function to print menu
+function menu {
+	font_options+=("Quit")
+	echo "${BLUE}Select one or more fonts:${reset}"
+	for i in "${!font_options[@]}"; do
+		printf "%d) %s\n" "$((i + 1))" "${font_options[$i]}"
+	done | pr -3 -t -w $(tput cols)
+}
+
+# call the menu funciton to list the available fonts
+menu
+
+# Parse input like 1-3
+function parse_range {
+	if ! [[ $1 =~ ^[0-9]+-[0-9]+$ ]]; then
+		echo "${RED}Invalid input format: $1. Expected format: X-Y.${RESET}"
+		return 1
+	fi
+	IFS='-' read -ra range <<<"$1"
+	range_start=${range[0]}
+	range_end=${range[1]}
+	for ((i = range_start; i <= range_end; i++)); do
+		index=$((i - 1))
+		if ((index >= 0 && index < ${#font_options[@]})); then
+			if [[ ${font_options[index]} != "Quit" ]]; then
+				selected_fonts[index]=${font_options[index]}
+			fi
+		else
+			echo "${RED}Invalid option: $i. Try again.${RESET}"
+			return 1
+		fi
+	done
+}
+
+## Handle user input
+while true; do
+	read -p "${BLUE}Enter font number(s) (e.g. 1,2,3 or 1-3 or 1,3-5):${RESET} " choices
+	for choice in $(echo $choices | tr ',' ' '); do
+		# check if they entered a range (e.g. 1-3)
+		if [[ $choice == *-* ]]; then
+			parse_range $choice || continue 2
+		elif ((choice >= 1 && choice <= ${#font_options[@]})); then
+			index=$((choice - 1))
+			if [[ ${font_options[$index]} == "Quit" ]]; then
+				echo "${GREEN}Goodbye!${reset}"
+				exit
+			fi
+			selected_fonts[$index]=${font_options[$index]}
+		else
+			echo "${RED}Invalid option: $choice. Try again.${RESET}"
+			continue 2
+		fi
+	done
+	break
+done
+
+# loop over the selected fonts and download them
+if ((${#selected_fonts[@]} > 0)); then
+	for i in "${selected_fonts[@]}"; do
+		pushd "$down_dir" >/dev/null
+		# remove the zip file of the download font if it exsists, this is due to curl not having an overwirte function
+		if [ -f $down_dir/$i.zip ]; then
+			rm $down_dir/$i.zip
+		fi
+		download_font $i &&
+			install_font $i &&
+			echo $i >>"$installed_fonts_file"
+		aFontInstalled=True
+		popd >/dev/null
+	done
+else
+	echo "${RED}No fonts were selected selected, exiting.${RESET}"
+	exit
+fi
+
+# If a font was installed
+if [ "$aFontInstalled" = "True" ]; then
+	# Update the fonts cache
+	update_fonts_cache
+	# remove downloaded archives if the option -k was not passed
+	if [ "$removeZipFiles" = "True" ]; then
+		remove_zip_files
+	else
+		echo "${GREEN}The downloaded zip files can be found in $down_dir${RESET}"
+	fi
+fi
+
+echo "${GREEN}Enjoy your new fonts!${RESET}"
